/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cassette(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./cassette_tape/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cassette.geometry}
        material={nodes.Cassette.material}
        position={[0, 0.19, -0.04]}
      />
    </group>
  )
}

useGLTF.preload('./cassete_tape/scene.gltf')